# Generated by Django 5.2.17 on 2026-09-19 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('finish_location', models.CharField(max_length=255)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('finish_latitude', models.FloatField()),
                ('finish_longitude', models.FloatField()),
                ('total_distance_miles', models.FloatField()),
                ('total_duration_seconds', models.FloatField()),
                ('total_fuel_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gallons', models.FloatField()),
                ('route_geometry', models.JSONField()),
                ('fuel_stops', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=8)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('price_per_gallon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_fue_latitud_6dc999_idx'), models.Index(fields=['price_per_gallon'], name='routing_fue_price_p_d32ca8_idx')],
            },
        ),
    ]
